config/routes.rb
Tesis::Application.routes.draw do
  
  resources :sugerencias

  resources :auditorias

  resources :donaciones

  resources :solvencias

  resources :devoluciones

  resources :alquileres

  resources :configuraciones

  resources :noticias

  controller :sesiones do

	get 'login' => :nuevo
	post 'login' => :crear
	delete 'logout' => :eliminar

  end

  resources :usuarios  

  resources :lines_items

  resources :carts

  get "ppal_admin/index"

  get "ppal_admin/adquiridos"

  get "informacion/historia"

  get "informacion/servicios"

  get "informacion/normativas"

  get "informacion/horarios"

  get "inicio/index"

  get "inicio/catalogo"
 	 
  get "inicio/catalogo_categorias"

  get "inicio/olvido_clave"
  
  post "inicio/olvido_clave"

  post "ppal_estudiante/guardar_solicitud_solvencia"	
  
  get "ppal_estudiante/index"

  get "ppal_estudiante/ecatalogo_categorias"

  get "ppal_estudiante/ver_alquiler"
  
  get "ppal_estudiante/ver_datos"
   
  get "ppal_estudiante/ver_ejemplar"

  get "ppal_estudiante/ver_libro"

  get "ppal_estudiante/confirmar_alquiler"

  get "ppal_estudiante/realizar_sugerencia"

  get "ppal_estudiante/ver_solvencias"

  get "ppal_estudiante/enviar_solicitud_solvencia"
  
  get "ejemplares/index"

  get "libros/index"
  post "libros/busqueda"
  get "editoriales/index"

  get "areas_conocimientos/index"

  get "dependencias/index"
  
  get "librerias/index"
 
  get "reportes/comprobante_alquiler"

  get "reportes/libros_alquilados"
  
  get "reportes/total_libros_alquilados"

  get "reportes/libros_adquiridos"
  
  post "reportes/libros_adquiridos"

  get "reportes/num_alquiler_escuela"
 
  get "reportes/libros_sin_alquiler"

  post "reportes/solvencia"

  get "reportes/deudores"
   
  get "donaciones/buscar_usuario"

  resources :ejemplares

  resources :libros  do
   get :autocomplete_libro_titulo, :on => :collection
  end

  resources :editoriales

  resources :areas_conocimientos

  resources :dependencias

  resources :librerias

  scope '(:locale)' do
	  resources :auditorias
	  resources :donaciones
	  resources :solvencias
	  resources :devoluciones
	  resources :alquileres
	  resources :configuraciones
	  resources :noticias
	  resources :libros
	  resources :ejemplares
	  resources :libros 
	  resources :editoriales
	  resources :areas_conocimientos
	  resources :dependencias
	  resources :librerias  
      resources :usuarios  
      resources :lines_items
  	  resources :carts
  	  resources :sugerencias	
	   root :to => 'inicio#index'
  end	

end

app/models/sugerencia.rb
class Sugerencia < ActiveRecord::Base
end

app/controllers/sugerencias_controller.rb
class SugerenciasController < ApplicationController
  # GET /sugerencias
  # GET /sugerencias.json
  layout "administrador"
  add_breadcrumb "Mantenimiento", :ppal_admin_index_path
  
  def index

	add_breadcrumb "Listado de sugerencias", :libros_index_path

    @sugerencias = Sugerencia.paginate(:page => params[:page], :per_page => 5)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @sugerencias }
    end
  end

  # GET /sugerencias/1
  # GET /sugerencias/1.json
  def show
    @sugerencia = Sugerencia.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @sugerencia }
    end
  end

  # GET /sugerencias/new
  # GET /sugerencias/new.json
  def new
    @sugerencia = Sugerencia.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @sugerencia }
    end
  end

  # GET /sugerencias/1/edit
  def edit
    @sugerencia = Sugerencia.find(params[:id])
  end

  # POST /sugerencias
  # POST /sugerencias.json
  def create
    @sugerencia = Sugerencia.new(params[:sugerencia])

    respond_to do |format|
      if @sugerencia.save
        format.html { redirect_to @sugerencia, :notice => 'Sugerencia was successfully created.' }
        format.json { render :json => @sugerencia, :status => :created, :location => @sugerencia }
      else
        format.html { render :action => "new" }
        format.json { render :json => @sugerencia.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sugerencias/1
  # PUT /sugerencias/1.json
  def update
    @sugerencia = Sugerencia.find(params[:id])

    respond_to do |format|
      if @sugerencia.update_attributes(params[:sugerencia])
        format.html { redirect_to @sugerencia, :notice => 'Sugerencia was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @sugerencia.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sugerencias/1
  # DELETE /sugerencias/1.json
  def destroy
    @sugerencia = Sugerencia.find(params[:id])
    @sugerencia.destroy

    respond_to do |format|
      format.html { redirect_to sugerencias_url }
      format.json { head :ok }
    end
  end
end

app/helpers/sugerencias_helper.rb
module SugerenciasHelper
end

app/views/sugerencias/_form.html.erb
<%= form_for(@sugerencia) do |f| %>
  <% if @sugerencia.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sugerencia.errors.count, "error") %> prohibited this sugerencia from being saved:</h2>

      <ul>
      <% @sugerencia.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fecha %><br />
    <%= f.date_select :fecha %>
  </div>
  <div class="field">
    <%= f.label :usuario %><br />
    <%= f.text_field :usuario %>
  </div>
  <div class="field">
    <%= f.label :libro %><br />
    <%= f.text_field :libro %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sugerencias/edit.html.erb
<h1>Editing sugerencia</h1>

<%= render 'form' %>

<%= link_to 'Show', @sugerencia %> |
<%= link_to 'Back', sugerencias_path %>

app/views/sugerencias/index.html.erb
<h1>Listing sugerencias</h1>

<table>
  <tr>
    <th>Fecha</th>
    <th>Usuario</th>
    <th>Libro</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sugerencias.each do |sugerencia| %>
  <tr>
    <td><%= sugerencia.fecha %></td>
    <td><%= sugerencia.usuario %></td>
    <td><%= sugerencia.libro %></td>
    <td><%= link_to 'Show', sugerencia %></td>
    <td><%= link_to 'Edit', edit_sugerencia_path(sugerencia) %></td>
    <td><%= link_to 'Destroy', sugerencia, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sugerencia', new_sugerencia_path %>

app/views/sugerencias/new.html.erb
<h1>New sugerencia</h1>

<%= render 'form' %>

<%= link_to 'Back', sugerencias_path %>

app/views/sugerencias/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Usuario:</b>
  <%= @sugerencia.usuario %>
</p>

<p>
  <b>Listado:</b>
  <%= @sugerencia.listado %>
</p>


<%= link_to 'Edit', edit_sugerencia_path(@sugerencia) %> |
<%= link_to 'Back', sugerencias_path %>