config/routes.rb
Tesis::Application.routes.draw do
  
  resources :sugerencias

  resources :auditorias

  resources :donaciones

  resources :solvencias

  resources :devoluciones

  resources :alquileres

  resources :configuraciones

  resources :noticias

  controller :sesiones do

	get 'login' => :nuevo
	post 'login' => :crear
	delete 'logout' => :eliminar

  end

  resources :usuarios  

  resources :lines_items

  resources :carts

  get "ppal_admin/index"

  get "ppal_admin/adquiridos"

  get "informacion/historia"

  get "informacion/servicios"

  get "informacion/normativas"

  get "informacion/horarios"

  get "inicio/index"

  get "inicio/catalogo"
 	 
  get "inicio/catalogo_categorias"

  get "inicio/olvido_clave"
  
  post "inicio/olvido_clave"

  post "ppal_estudiante/guardar_solicitud_solvencia"	
  
  get "ppal_estudiante/index"

  get "ppal_estudiante/ecatalogo_categorias"

  get "ppal_estudiante/ver_alquiler"
  
  get "ppal_estudiante/ver_datos"
   
  get "ppal_estudiante/ver_ejemplar"

  get "ppal_estudiante/ver_libro"

  get "ppal_estudiante/confirmar_alquiler"

  get "ppal_estudiante/realizar_sugerencia"

  get "ppal_estudiante/ver_solvencias"

  get "ppal_estudiante/enviar_solicitud_solvencia"
  
  get "ejemplares/index"

  get "libros/index"
  post "libros/busqueda"
  get "editoriales/index"

  get "areas_conocimientos/index"

  get "dependencias/index"
  
  get "librerias/index"
 
  get "reportes/comprobante_alquiler"

  get "reportes/libros_alquilados"
  
  get "reportes/total_libros_alquilados"

  get "reportes/libros_adquiridos"
  
  post "reportes/libros_adquiridos"

  get "reportes/num_alquiler_escuela"
 
  get "reportes/libros_sin_alquiler"

  post "reportes/solvencia"

  get "reportes/deudores"
   
  get "donaciones/buscar_usuario"

  resources :ejemplares

  resources :libros  do
   get :autocomplete_libro_titulo, :on => :collection
  end

  resources :editoriales

  resources :areas_conocimientos

  resources :dependencias

  resources :librerias

  scope '(:locale)' do
	  resources :auditorias
	  resources :donaciones
	  resources :solvencias
	  resources :devoluciones
	  resources :alquileres
	  resources :configuraciones
	  resources :noticias
	  resources :libros
	  resources :ejemplares
	  resources :libros 
	  resources :editoriales
	  resources :areas_conocimientos
	  resources :dependencias
	  resources :librerias  
      resources :usuarios  
      resources :lines_items
  	  resources :carts
  	  resources :sugerencias	
	   root :to => 'inicio#index'
  end	

end

app/models/solvencia.rb
class Solvencia < ActiveRecord::Base
  belongs_to :usuario
end

app/controllers/solvencias_controller.rb
class SolvenciasController < ApplicationController
   before_filter :es_adminitrador
   layout "administrador"

  # GET /solvencias
  # GET /solvencias.json
  def index
    @search = Solvencia.order('created_at desc').search(params[:search])
	@solvencias = @search.paginate(:page => params[:page], :per_page => 5)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @solvencias }
    end
  end

  # GET /solvencias/1
  # GET /solvencias/1.json
  def show
    @solvencia = Solvencia.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @solvencia }
    end
  end

  # GET /solvencias/new
  # GET /solvencias/new.json
  def new
    @solvencia = Solvencia.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @solvencia }
    end
  end

  # GET /solvencias/1/edit
  def edit
    @solvencia = Solvencia.find(params[:id])
  end

  # POST /solvencias
  # POST /solvencias.json
  def create
    @solvencia = Solvencia.new(params[:solvencia])

    respond_to do |format|
      if @solvencia.save
		guardar_log(session[:usuario_id], self.class.name,__method__.to_s, @solvencia,nil )
        format.html { redirect_to @solvencia, :notice => 'Solvencia was successfully created.' }
        format.json { render :json => @solvencia, :status => :created, :location => @solvencia }
      else
        format.html { render :action => "new" }
        format.json { render :json => @solvencia.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /solvencias/1
  # PUT /solvencias/1.json
  def update
    @solvencia = Solvencia.find(params[:id])
	@temp = @solvencia.dup
	@solvencia.estatus= "Solvencia Entregada"		

    respond_to do |format|
      if @solvencia.update_attributes(params[:solvencia])
		guardar_log(session[:usuario_id], self.class.name,__method__.to_s, @temp,@solvencia )
        format.html { redirect_to :action => "index" }
        format.json { head :ok }
      else
        format.html { redirect_to  :action => "index", :notice => "No se pudo guardar los cambios, por favor intente más tarde"  }
        format.json { head :ok }

      end
    end
  end

  # DELETE /solvencias/1
  # DELETE /solvencias/1.json
  def destroy
    @solvencia = Solvencia.find(params[:id])
	@temp = @solvencia.dup
    @solvencia.destroy
	guardar_log(session[:usuario_id], self.class.name,__method__.to_s, @temp,nil )
    respond_to do |format|
      format.html { redirect_to solvencias_url }
      format.json { head :ok }
    end
  end
end

app/helpers/solvencias_helper.rb
module SolvenciasHelper
end

app/views/solvencias/_form.html.erb
<%= form_for(@solvencia) do |f| %>
  <% if @solvencia.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@solvencia.errors.count, "error") %> prohibited this solvencia from being saved:</h2>

      <ul>
      <% @solvencia.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :estatus %><br />
    <%= f.text_field :estatus %>
  </div>
  <div class="field">
    <%= f.label :usuario %><br />
    <%= f.text_field :usuario %>
  </div>
  <div class="field">
    <%= f.label :tipo_solvencia %><br />
    <%= f.text_field :tipo_solvencia %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/solvencias/edit.html.erb
<h1>Editing solvencia</h1>

<%= render 'form' %>

<%= link_to 'Show', @solvencia %> |
<%= link_to 'Back', solvencias_path %>

app/views/solvencias/index.html.erb
<% if flash[:notice] %>
	<p class="notice"><%= flash[:notice] %></p>
<% end %>



<div class ="busqueda">
  <%= form_for @search do |f| %>
    <%= f.text_field :usuario_cedula_contains, :value => "Buscar por cédula", :onfocus =>"this.value=''", :onblur =>"this.value='Buscar por cédula'", :class => "campo_busqueda" %>
      
    <%= f.submit :buscar %>
  <% end %>
</div>


<div class ="titulo"><h1>Listado de Solvencias</h1></div>

<%= will_paginate @solvencias , :previous_label => "Anterior", :next_label => "Siguiente", :class => "paginacion" %>

<table class="tabla_scaffold" width="98%">

<% @solvencias.each do |solvencia| %>
  <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
 	 <td class="list_description">
			<dl>
				<dt>Nro Solvencia : <%= solvencia.id %></dt>
				<dd>Estatus: <%= solvencia.estatus %>  </dd>    	
				<dd>Cédula: <%= link_to solvencia.usuario.cedula,solvencia.usuario  %></dd>
				<dd>Nombre: <%= link_to solvencia.usuario.nombre, solvencia.usuario   %></dd>
				<dd>Tipo: <%= solvencia.tipo_solvencia %></dd>
				<dd>Fecha de Solicitud: <%= solvencia.created_at.strftime("%d/%m/%Y") %> </dd>
			</dl>
		</td>
		<td class="list_actions" width="5%">
			<%= link_to image_tag("icon_pdf.gif", :alt => "PDF", :title => "PDF", :size => "18x18"), {:controller => "reportes", :action => "solvencia", :usuario_id => solvencia.usuario.id }, :target => "_blank", :method => :post%><br />

			<%= link_to image_tag("check.gif", :alt => "Marcar como entregada", :title => "Marcar como entregada", :size => "18x18"), solvencia, :method => :put%><br />	
			
		</td>  
  </tr>
<% end %>
</table>

<%= will_paginate @solvencias , :previous_label => "Anterior", :next_label => "Siguiente", :class => "paginacion" %>

<br />

app/views/solvencias/new.html.erb
<h1>New solvencia</h1>

<%= render 'form' %>

<%= link_to 'Back', solvencias_path %>

app/views/solvencias/show.html.erb
<% if notice %>
<p class="notice"><%= notice %></p>
<% end %>
<p>
  <b>Estatus:</b>
  <%= @solvencia.estatus %>
</p>

<p>
  <b>Usuario:</b>
  <%= @solvencia.usuario %>
</p>

<p>
  <b>Tipo solvencia:</b>
  <%= @solvencia.tipo_solvencia %>
</p>

<br />
<%= link_to 'Editar', edit_solvencia_path(@solvencia) %> |
<%= link_to 'Regresar', solvencias_path %>