config/routes.rb
Tesis::Application.routes.draw do
  
  resources :sugerencias

  resources :auditorias

  resources :donaciones

  resources :solvencias

  resources :devoluciones

  resources :alquileres

  resources :configuraciones

  resources :noticias

  controller :sesiones do

	get 'login' => :nuevo
	post 'login' => :crear
	delete 'logout' => :eliminar

  end

  resources :usuarios  

  resources :lines_items

  resources :carts

  get "ppal_admin/index"

  get "ppal_admin/adquiridos"

  get "informacion/historia"

  get "informacion/servicios"

  get "informacion/normativas"

  get "informacion/horarios"

  get "inicio/index"

  get "inicio/catalogo"
 	 
  get "inicio/catalogo_categorias"

  get "inicio/olvido_clave"
  
  post "inicio/olvido_clave"

  post "ppal_estudiante/guardar_solicitud_solvencia"	
  
  get "ppal_estudiante/index"

  get "ppal_estudiante/ecatalogo_categorias"

  get "ppal_estudiante/ver_alquiler"
  
  get "ppal_estudiante/ver_datos"
   
  get "ppal_estudiante/ver_ejemplar"

  get "ppal_estudiante/ver_libro"

  get "ppal_estudiante/confirmar_alquiler"

  get "ppal_estudiante/realizar_sugerencia"

  get "ppal_estudiante/ver_solvencias"

  get "ppal_estudiante/enviar_solicitud_solvencia"
  
  get "ejemplares/index"

  get "libros/index"
  post "libros/busqueda"
  get "editoriales/index"

  get "areas_conocimientos/index"

  get "dependencias/index"
  
  get "librerias/index"
 
  get "reportes/comprobante_alquiler"

  get "reportes/libros_alquilados"
  
  get "reportes/total_libros_alquilados"

  get "reportes/libros_adquiridos"
  
  post "reportes/libros_adquiridos"

  get "reportes/num_alquiler_escuela"
 
  get "reportes/libros_sin_alquiler"

  post "reportes/solvencia"

  get "reportes/deudores"
   
  get "donaciones/buscar_usuario"

  resources :ejemplares

  resources :libros  do
   get :autocomplete_libro_titulo, :on => :collection
  end

  resources :editoriales

  resources :areas_conocimientos

  resources :dependencias

  resources :librerias

  scope '(:locale)' do
	  resources :auditorias
	  resources :donaciones
	  resources :solvencias
	  resources :devoluciones
	  resources :alquileres
	  resources :configuraciones
	  resources :noticias
	  resources :libros
	  resources :ejemplares
	  resources :libros 
	  resources :editoriales
	  resources :areas_conocimientos
	  resources :dependencias
	  resources :librerias  
      resources :usuarios  
      resources :lines_items
  	  resources :carts
  	  resources :sugerencias	
	   root :to => 'inicio#index'
  end	

end

app/models/libro.rb
class Libro < ActiveRecord::Base
  belongs_to :editorial
  belongs_to :area_conocimiento
  belongs_to :dependencia
  has_many :ejemplar 
  
 
  attr_accessor :libro_titulo
  

  validates :cota, :titulo, :autor,:edicion, :ano, :presence => true  
  validates :cota, :isbn,  :uniqueness => true

  has_attached_file :imagen, :styles => { :medium => "300x300>", :thumb => "60x60>" }

  def titulo_and_autor
  	[titulo,autor].join(' | ')
  end
  public 

  public
  def cantidad_disponible
    ejemplar.where("estatus_ejemplar = 'Disponible' ").count      
		  		
  end

 def precio_minimo 	
	min = ejemplar.where("estatus_ejemplar = 'Disponible' or estatus_ejemplar = 'Solicitado'").order('costo_alquiler asc').first
	if min.nil?
		return 0
	else
		return min.costo_alquiler
	end	

 end 	
 	
 def precio_maximo
	ejemplar.where("estatus_ejemplar = 'Disponible' or estatus_ejemplar = 'Solicitado'").order('costo_alquiler asc').last.costo_alquiler 
 end


end

app/controllers/libros_controller.rb
require 'googlebooks'

class LibrosController < ApplicationController
	before_filter :es_adminitrador
  	skip_before_filter :es_adminitrador, :only => :autocomplete_libro_titulo

	layout "administrador"
    add_breadcrumb "Mantenimiento", :ppal_admin_index_path

	autocomplete :libro, :titulo
  # GET /libros
  # GET /libros.json
  def index


	add_breadcrumb "Listado de libros", :libros_index_path
	@search = Libro.search(params[:search])
    @libros = @search.paginate(:page => params[:page], :per_page => 5)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @libros }
    end
  end

  # GET /libros/1
  # GET /libros/1.json
  def show
	add_breadcrumb "Datos del libro", :libro_path
    @libro = Libro.find(params[:id])
		
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @libro }
    end
  end

  # GET /libros/new
  # GET /libros/new.json
  def new
	add_breadcrumb "Nuevo libro", :new_libro_path
    @libro = Libro.new
	
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @libro }
    end
  end

  def busqueda

    @isbn = params[:isbn]
	@books = GoogleBooks.search('isbn:'+@isbn)
	if !@books.first.nil?	
		first_book = @books.first
		@imagen = first_book.image_link
		@autor = first_book.authors 
		@titulo = first_book.title
		@editorial = first_book.publisher 
		@isbn = first_book.isbn 	
		@ano = first_book.published_date 
	end
	add_breadcrumb "Nuevo libro", :new_libro_path
    @libro = Libro.new
	
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @libro }
    end
  end

  # GET /libros/1/edit
  def edit
	add_breadcrumb "Editar libro", :edit_libro_path
    @libro = Libro.find(params[:id])
  end

  # POST /libros
  # POST /libros.json
  def create
    @libro = Libro.new(params[:libro])

    respond_to do |format|
      if @libro.save
		guardar_log(session[:usuario_id], self.class.name,__method__.to_s, @libro,nil )
        format.html { redirect_to @libro, :notice => 'Libro creado exitosamente.' }
        format.json { render :json => @libro, :status => :created, :location => @libro }
      else
        format.html { render :action => "new" }
        format.json { render :json => @libro.errors, :status => :unprocessable_entity }
      end
    end



  end

  # PUT /libros/1
  # PUT /libros/1.json
  def update
    @libro = Libro.find(params[:id])
	@temp = @libro.dup
    respond_to do |format|
      if @libro.update_attributes(params[:libro])
		guardar_log(session[:usuario_id], self.class.name,__method__.to_s, @temp,@libro  )

        format.html { redirect_to @libro, :notice => 'Libro actualizado exitosamente.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @libro.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /libros/1
  # DELETE /libros/1.json
  def destroy
    @libro = Libro.find(params[:id])
	@temp = @libro.dup
    @libro.destroy
	guardar_log(session[:usuario_id], self.class.name,__method__.to_s, @temp,nil )
    respond_to do |format|
      format.html { redirect_to libros_url, :notice => 'Libro eliminado exitosamente.'  }
      format.json { head :ok }
    end
  end


end

app/helpers/libros_helper.rb
module LibrosHelper
end

app/views/libros/_form.html.erb
<%= form_for(@libro) do |f| %>
  <% if @libro.errors.any? %>
    <div id="error_explanation">
     <h2><%= t('errors.template.header', :count=>@libro.errors.size,:model=>t('activerecord.models.libro')) %>.</h2>
	 <p><%= t('errors.template.body') %></p>


      <ul>
      <% @libro.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cota %><br />
    <%= f.text_field :cota %>
  </div>
  <div class="field">
    <%= f.label :titulo %><br />
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :autor %><br />
    <%= f.text_field :autor %>
  </div>
  <div class="field">
    <%= f.label :imagen %><br />
    <%= f.file_field :imagen %>
  </div>
  <div class="field">
    <%= f.label :edicion %><br />
    <%= f.number_field :edicion %>
  </div>
  <div class="field">
    <%= f.label :lugar_impresion %><br />
    <%= f.text_field :lugar_impresion %>
  </div>
  <div class="field">
    <%= f.label :ano %><br />
    <%= f.number_field :ano %>
  </div>
  <div class="field">
    <%= f.label :isbn %><br />
    <%= f.text_field :isbn %>
  </div>
  <div class="field">
    <%= f.label :editorial %><br />
    <%= f.collection_select :editorial_id, Editorial.all, :id, :nombre %>
  </div>
  <div class="field">
    <%= f.label :area_conocimiento %><br />
    <%= f.collection_select :area_conocimiento_id, AreaConocimiento.all, :id, :nombre %>
  </div>
  <div class="field">
    <%= f.label :dependencia %><br />
    <%= f.collection_select :dependencia_id, Dependencia.all, :id, :nombre %>
  </div>
  <div class="actions">
    <%= f.submit t('.submit') %>
  </div>
<% end %>

app/views/libros/_total_libro.html.erb
	<h3>Cantidad disponible:  <%= libro.cantidad_disponible  %>  </h3>		

app/views/libros/busqueda.html.erb
<div class = "editar">

	<div class = "editar_titulo"><h1>Resultados de la búsqueda</h1></div>

	<div class = "editar_opciones">
		<%= link_to 'Regresar', :back, :id => "links" %>
	</div>

	<div class="clear"></div>

</div>
<% if @books.first.nil? %>
	<div class = "notice"><p>No se encontraron resultados.</p></div>

<% else %>

<div class = "mostrar"><br /><br />


	<div class="buscar_imagen">
	<% if @imagen.nil? %>
	 <%= image_tag("libro.png",:class => 'list_image') %>
	<% else %>
	 <%= image_tag(@imagen,:class => 'list_image' )  %>
	<% end %>
	</div>

	<%= form_for(@libro) do |f| %>

	  <% if @libro.errors.any? %>
		<div id="error_explanation">
		 <h2><%= t('errors.template.header', :count=>@libro.errors.size,:model=>t('activerecord.models.libro')) %>.</h2>
		 <p><%= t('errors.template.body') %></p>

		  <ul>
		  <% @libro.errors.full_messages.each do |msg| %>
		    <li><%= msg %></li>
		  <% end %>
		  </ul>
		</div>
	  <% end %>


	  <div class="field">
		<%= f.label :cota %><br />
		<%= f.text_field :cota %>
	  </div>
	  <div class="field">
		<%= f.label :titulo %><br />
		<%= f.text_field :titulo, :value => @titulo %>
	  </div>
	  <div class="field">
		<%= f.label :autor %><br />
		<%= f.text_field :autor, :value =>  @autor %>
	  </div>
	  <div class="field">
		<%= f.label :imagen %><br />
		<% if @imagen.nil? %>
		<%= f.file_field :imagen %>
		<% else %>
		<%= f.text_field :imagen, :value =>  @imagen %>
		<% end %>
	  </div>
	  <div class="field">
		<%= f.label :edicion %><br />
		<%= f.number_field :edicion %>
	  </div>
	  <div class="field">
		<%= f.label :lugar_impresion %><br />
		<%= f.text_field :lugar_impresion %>
	  </div>
	  <div class="field">
		<%= f.label :ano %><br />
		<%= f.number_field :ano, :value =>  @ano %>
	  </div>
	  <div class="field">
		<%= f.label :isbn %><br />
		<%= f.text_field :isbn, :value =>  @isbn %>
	  </div>
	  <div class="field">
		<%= f.label :editorial %><br />
		<% if @editorial.nil? %>
		 <%= f.collection_select :editorial_id, Editorial.all, :id, :nombre %>
		<% else %>
		 <%= f.text_field :editorial_id, :value =>  @editorial %>
		<% end %>
	  </div>
	  <div class="field">
		<%= f.label :area_conocimiento %><br />
		<%= f.collection_select :area_conocimiento_id, AreaConocimiento.all, :id, :nombre %>
	  </div>
	  <div class="field">
		<%= f.label :dependencia %><br />
		<%= f.collection_select :dependencia_id, Dependencia.all, :id, :nombre %>
	  </div>
	  <div class="actions">
		<%= f.submit t('.submit') %>
	  </div>

	<% end %>

</div>

<% end %>

app/views/libros/edit.html.erb
<div class = "editar">
	<div class = "editar_titulo"><h1>Editar libro</h1></div>

	<div class = "editar_opciones">
	<%= link_to 'Regresar', :back, :id => "links" %>
	</div>
	<div class="clear"></div>
</div>

<div class = "mostrar"><%= render 'form' %></div>

app/views/libros/index.html.erb
<% if notice %>
	<p class="notice"><%= notice %></p>
<% end %>
<script>
      $(document).ready(function () {
          $("#search_cota_or_isbn_or_titulo_contains").onfocus(function () {
              var value = $(this).val();
              $("#search_cota_or_isbn_or_titulo_contains").val(value);
          });
      });
</script>
<div class ="busqueda">
  <%= form_for @search do |f| %>

    <%= f.autocomplete_field :cota_or_isbn_or_titulo_contains, autocomplete_libro_titulo_libros_path, :value => "Buscar por cota, isbn o título", :onfocus =>"this.value=''", :id => "buscar" %>   

    <%= f.submit :buscar, :id => "btn_buscar" %>

  <% end %>
</div>

<div class ="titulo"><h1>Listado de libros</h1></div>
<%= link_to 'Nuevo Libro', new_libro_path, :id => "links" %>
<div style="line-height:25px;display: block;margin-bottom:30px;margin-top:20px;">


	<div style="font-size:12px;float:left;">
	  Ordenar por:
	  <%= sort_link @search, :cota %> |
	  <%= sort_link @search, :isbn %> |
	  <%= sort_link @search, :titulo %>

	</div>
	
	<%= will_paginate(@libros, :renderer => PaginationListLinkRenderer, :first_label => "Primera",
	  :previous_label => "Anterior",
	  :summary_label => "%d - %d de %d",
	  :next_label => "Siguiente",
	  :last_label => "Última") %>
</div>

<table class="tabla_scaffold" width="100%">
	<% @libros.each do |libro| %>
	<tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
		<td width="5%">
			<% if libro.imagen_file_name == nil %>
				<% if libro.isbn != nil %>
					<% @isbn = ('isbn:' + libro.isbn) %>
					<% @books = GoogleBooks.search('isbn:'+libro.isbn.gsub("-","")) %>
					<% if @books.first.nil? %>
						<%= image_tag("libro.png",:class => 'list_image') %>				
				
					<% else %>
						<%= image_tag(@books.first.image_link,:class => 'list_image' )  %>
					<% end %>		
				<% else %>
					<%= image_tag("libro.png",:class => 'list_image') %>						
				<% end %>	
			<% else %>
				<%= image_tag(libro.imagen.url(:thumb),:class => 'list_image') %>
			<% end %>
		</td>
		<td class="list_description">
			<dl>
				<dt><%= libro.titulo %></dt>
				<dd><%= libro.cota %></dd>
				<dd>Autor: <%= libro.autor %></dd>
				<dd>Isbn: <%= libro.isbn %></dd>
			</dl>
		</td>
		<td class="list_actions" width="5%">
			<%= link_to image_tag("open.png", :alt => "Mostrar", :title => "Mostrar", :size => "18x18"), libro %><br />
			<%= link_to image_tag("editpaste.png", :alt => "Editar", :title => "Editar", :size => "18x18"), edit_libro_path(libro) %><br />
			<%= link_to image_tag("cross.png", :alt => "Eliminar", :title => "Eliminar", :size => "18x18"), libro, :confirm => '¿Estas seguro?', :method => :delete %>
		</td>
	</tr>
	<% end %>
</table>

<%= will_paginate @libros , :previous_label => "Anterior", :next_label => "Siguiente", :class => "paginacion" %>

app/views/libros/new.html.erb
<div class = "editar">

	<div class = "editar_titulo"><h1>Nuevo libro</h1></div>

	<div class = "editar_opciones">
		<%= link_to 'Regresar', libros_index_path, :id => "links" %>
	</div>

	<div class="clear"></div>

</div>

<div class = "mostrar">

	<%= form_tag url_for (:controller => "libros",:action => "busqueda") do %>

		<div class="buscar_isbn">
			<%= label :isbn, 'Buscar por ISBN' %><br />
			<%= text_field_tag :isbn, params[:isbn], :id => "buscar" %>
			<%= submit_tag "buscar", :id => 'btn_buscar' %>
		</div>
	<% end %>

	<%= render 'form' %>

</div>

app/views/libros/show.html.erb
<% if notice %>
<p class="notice"><%= notice %></p>
<% end %>
<div class = "mostrar">
<p>
  <b>Cota:</b>
  <%= @libro.cota %>
</p>

<p>
  <b>Titulo:</b>
  <%= @libro.titulo %>
</p>

<p>
  <b>Autor:</b>
  <%= @libro.autor %>
</p>

<p>
  <b>Imagen:</b>
  <%= image_tag @libro.imagen.url(:thumb) %>
</p>

<p>
  <b>Edicion:</b>
  <%= @libro.edicion %>
</p>

<p>
  <b>Lugar impresion:</b>
  <%= @libro.lugar_impresion %>
</p>

<p>
  <b>Ano:</b>
  <%= @libro.ano %>
</p>

<p>
  <b>Isbn:</b>
  <%= @libro.isbn %>
</p>

<p>
  <b>Editorial:</b>
  <%= link_to @libro.editorial.nombre, @libro.editorial %>
</p>

<p>
  <b>Area conocimiento:</b>
  <%= link_to @libro.area_conocimiento.nombre,@libro.area_conocimiento %>
</p>

<p>
  <b>Dependencia:</b>
  <%= link_to @libro.dependencia.nombre, @libro.dependencia %>
</p>
</div>
<br />
<%= link_to 'Editar', edit_libro_path(@libro), :id => "links" %> &nbsp
<%= link_to 'Regresar', :back, :id => "links" %>